version: "3.9"
services:
  jupyterlab:
    image: jhebeler/classtank:705.603.jupyterlab
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "8889:8888"
      - "8787:8787"
      - "8786:8786"
      - "5001:5000"
    volumes:
      - ./workspace:/rapids/notebooks/workspace
    command:
      [
        'jupyter',
        'lab',
        '--no-browser',
        '--ip=0.0.0.0',
        '--allow-root'
      ]
